import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Writes src/gmux/katybug/libm-sigs.h: musl's exp, log and pow as a static program carries them,
 * each function's machine code in a libc.a (length, first eight bytes, FNV-1a hash) with the bits
 * the linker fills in left out (the offsets and masks of its relocations), since a table or a
 * helper sits at another address in every program.
 * `node --experimental-strip-types tests/c/katybug/libm-sigs.ts <x86 libc.a> <a64 libc.a> [llvm bin dir]`
 */
const [x86, a64, llvm = process.env.LLVM ?? '/opt/homebrew/opt/llvm/bin'] = process.argv.slice(2);
if (!x86 || !a64) {
	console.error('usage: libm-sigs.ts <x86 libc.a> <a64 libc.a> [llvm bin dir]');
	process.exit(2);
}
const names = ['exp', 'log', 'pow'];
const dir = mkdtempSync(join(tmpdir(), 'libm-sigs-'));

const fnv = (b: Uint8Array): bigint => {
	let h = 0xcbf29ce484222325n;
	for (const x of b) h = ((h ^ BigInt(x)) * 0x100000001b3n) & 0xffffffffffffffffn;
	return h;
};

// relocation type -> the bits it fills in (x86: whole 4-byte fields; AArch64: the immediate)
const masks: Record<string, Record<number, number>> = {
	x86: { 2: 0xffffffff, 4: 0xffffffff, 10: 0xffffffff, 11: 0xffffffff },
	a64: {
		273: 0x00ffffe0,
		274: 0x60ffffe0,
		275: 0x60ffffe0,
		277: 0x003ffc00,
		282: 0x03ffffff,
		283: 0x03ffffff,
		286: 0x003ffc00
	}
};

type Sec = { name: string; type: number; offset: number; size: number };

function sections(f: Buffer): Sec[] {
	const shoff = Number(f.readBigUInt64LE(0x28));
	const num = f.readUInt16LE(0x3c);
	const str = f.readUInt16LE(0x3e);
	const raw = Array.from({ length: num }, (_, i) => {
		const o = shoff + i * 64;
		return {
			nameOff: f.readUInt32LE(o),
			type: f.readUInt32LE(o + 4),
			offset: Number(f.readBigUInt64LE(o + 0x18)),
			size: Number(f.readBigUInt64LE(o + 0x20))
		};
	});
	const strtab = raw[str].offset;
	return raw.map((s) => {
		let end = strtab + s.nameOff;
		while (f[end] !== 0) end++;
		return {
			name: f.toString('latin1', strtab + s.nameOff, end),
			type: s.type,
			offset: s.offset,
			size: s.size
		};
	});
}

const out: string[] = [
	'/* generated by tests/c/katybug/libm-sigs.ts: musl 1.2.5-r3 (Alpine 3.20) exp, log and pow, with the relocated bits masked */'
];
const rows: string[] = [];
for (const [arch, libc] of [
	['x86', x86],
	['a64', a64]
] as const) {
	for (const [i, n] of names.entries()) {
		execFileSync(join(llvm, 'llvm-ar'), ['x', resolve(libc), `${n}.lo`], { cwd: dir });
		const f = readFileSync(join(dir, `${n}.lo`));
		const secs = sections(f);
		const text = secs.find((s) => s.name === `.text.${n}`);
		const rela = secs.find((s) => s.name === `.rela.text.${n}`);
		if (!text || !rela) throw new Error(`${arch} ${n}: no .text or .rela.text section`);
		const b = Buffer.from(f.subarray(text.offset, text.offset + text.size));
		const list: [number, number][] = [];
		for (let o = rela.offset; o < rela.offset + rela.size; o += 24) {
			const off = Number(f.readBigUInt64LE(o));
			const type = Number(f.readBigUInt64LE(o + 8) & 0xffffffffn);
			const mask = masks[arch][type];
			if (mask === undefined)
				throw new Error(`${arch} ${n}: relocation type ${type} at ${off}`);
			b.writeUInt32LE((b.readUInt32LE(off) & ~mask) >>> 0, off);
			list.push([off, mask]);
		}
		list.sort((p, q) => p[0] - q[0]);
		out.push(
			`static const struct libm_mask ${n}_${arch}[] = {${list.map(([o, m]) => `{${o}, 0x${m.toString(16)}u}`).join(', ')}};`
		);
		rows.push(
			`\t{KB_${arch.toUpperCase()}, ${i + 8}, ${b.length}, 0x${b.readBigUInt64LE(0).toString(16).padStart(16, '0')}ull, 0x${fnv(b).toString(16).padStart(16, '0')}ull, ${n}_${arch}, ${list.length}}, /* ${n} */`
		);
		if (arch === 'x86' || arch === 'a64')
			console.error(`${arch} ${n}: ${b.length} bytes, ${list.length} relocations`);
	}
}
out.push(
	'static const struct libm_sig {',
	'\tint arch, id;',
	'\tuint32_t len;',
	'\tuint64_t head, hash;',
	'\tconst struct libm_mask* mask;',
	'\tint nmask;',
	'} libm_sigs[] = {',
	...rows,
	'};'
);
const here = dirname(fileURLToPath(import.meta.url));
const file = join(here, '../../../src/gmux/katybug/libm-sigs.h');
writeFileSync(file, `${out.join('\n')}\n`);
// the repo's format check covers this file too
execFileSync('bash', [join(here, '../../../format.sh'), file], { stdio: 'inherit' });
