import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

/**
 * Prints the rows of src/gmux/katybug/prim.c's table (each string function's whole machine code in
 * a musl libc.a: length, first eight bytes, FNV-1a hash) and writes prim-bodies.h, the same bytes
 * as assembly for prim-faults.c.
 * `node --experimental-strip-types tests/c/katybug/prim-sigs.ts <x86 libc.a> <a64 libc.a> [llvm bin dir]`
 */
const [x86, a64, llvm = process.env.LLVM ?? '/opt/homebrew/opt/llvm/bin'] = process.argv.slice(2);
if (!x86 || !a64) {
	console.error('usage: prim-sigs.ts <x86 libc.a> <a64 libc.a> [llvm bin dir]');
	process.exit(2);
}
const names = ['strlen', 'memcmp', 'strcmp', 'memchr'];
const dir = mkdtempSync(join(tmpdir(), 'prim-sigs-'));

const fnv = (b: Buffer): bigint => {
	let h = 0xcbf29ce484222325n;
	for (const x of b) h = ((h ^ BigInt(x)) * 0x100000001b3n) & 0xffffffffffffffffn;
	return h;
};

const bodies: string[] = [
	'/* generated by prim-sigs.ts: musl 1.2.5-r3 (Alpine 3.20) string functions, byte for byte */'
];
for (const [arch, libc, guard] of [
	['x86', x86, '__x86_64__'],
	['a64', a64, '__aarch64__']
]) {
	bodies.push(`#if defined(${guard})`);
	for (const [i, n] of names.entries()) {
		execFileSync(join(llvm, 'llvm-ar'), ['x', libc, `${n}.lo`], { cwd: dir });
		execFileSync(
			join(llvm, 'llvm-objcopy'),
			['-O', 'binary', `--only-section=.text.${n}`, `${n}.lo`, `${n}.bin`],
			{ cwd: dir }
		);
		const b = readFileSync(join(dir, `${n}.bin`));
		console.log(
			`\t{KB_${arch.toUpperCase()}, ${i + 1}, ${b.length}, 0x${b.readBigUInt64LE(0).toString(16).padStart(16, '0')}ull, 0x${fnv(b).toString(16).padStart(16, '0')}ull}, /* ${n} */`
		);
		const hex = [...b].map((x) => `0x${x.toString(16).padStart(2, '0')}`).join(',');
		bodies.push(`__asm__(".text\\n.globl prim_${n}\\nprim_${n}:\\n.byte ${hex}\\n");`);
	}
	bodies.push('#endif');
}
const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, 'prim-bodies.h');
writeFileSync(out, `${bodies.join('\n')}\n`);
// the repo's format check covers this file too
execFileSync('bash', [join(here, '../../../format.sh'), out], { stdio: 'inherit' });
