#!/bin/sh
# x86-64 and AArch64 ELF executables (ET_EXEC or ET_DYN) run through katybug when exec'd
if [ -x /bin/katybug ] && mount -t binfmt_misc none /proc/sys/fs/binfmt_misc 2> /dev/null; then
	mask='\xff\xff\xff\xff\xff\xfe\xfe\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff'
	elf='\x7fELF\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00'
	echo ":x86_64:M::${elf}\x3e\x00:${mask}:/bin/katybug:" > /proc/sys/fs/binfmt_misc/register
	echo ":aarch64:M::${elf}\xb7\x00:${mask}:/bin/katybug:" > /proc/sys/fs/binfmt_misc/register
fi
