/* generated by tests/c/katybug/libm-sigs.ts: musl 1.2.5-r3 (Alpine 3.20) exp,
 * log and pow, with the relocated bits masked */
static const struct libm_mask exp_x86[] = {
    {37, 0xffffffffu},  {45, 0xffffffffu},  {52, 0xffffffffu},
    {77, 0xffffffffu},  {105, 0xffffffffu}, {128, 0xffffffffu},
    {156, 0xffffffffu}, {164, 0xffffffffu}, {172, 0xffffffffu},
    {261, 0xffffffffu}, {269, 0xffffffffu}, {275, 0xffffffffu},
    {308, 0xffffffffu}, {342, 0xffffffffu}, {381, 0xffffffffu},
    {442, 0xffffffffu}, {456, 0xffffffffu}
};
static const struct libm_mask log_x86[] = {
    {87, 0xffffffffu},  {98, 0xffffffffu},  {106, 0xffffffffu},
    {130, 0xffffffffu}, {200, 0xffffffffu}, {224, 0xffffffffu},
    {240, 0xffffffffu}, {276, 0xffffffffu}, {320, 0xffffffffu},
    {328, 0xffffffffu}, {336, 0xffffffffu}, {344, 0xffffffffu},
    {352, 0xffffffffu}, {376, 0xffffffffu}, {396, 0xffffffffu},
    {408, 0xffffffffu}, {424, 0xffffffffu}, {436, 0xffffffffu},
    {460, 0xffffffffu}, {472, 0xffffffffu}, {492, 0xffffffffu},
    {619, 0xffffffffu}, {655, 0xffffffffu}, {660, 0xffffffffu}
};
static const struct libm_mask pow_x86[] = {
    {119, 0xffffffffu},  {127, 0xffffffffu},  {136, 0xffffffffu},
    {167, 0xffffffffu},  {226, 0xffffffffu},  {247, 0xffffffffu},
    {260, 0xffffffffu},  {311, 0xffffffffu},  {338, 0xffffffffu},
    {399, 0xffffffffu},  {427, 0xffffffffu},  {559, 0xffffffffu},
    {567, 0xffffffffu},  {574, 0xffffffffu},  {599, 0xffffffffu},
    {628, 0xffffffffu},  {660, 0xffffffffu},  {684, 0xffffffffu},
    {692, 0xffffffffu},  {700, 0xffffffffu},  {930, 0xffffffffu},
    {1016, 0xffffffffu}, {1153, 0xffffffffu}, {1194, 0xffffffffu},
    {1225, 0xffffffffu}, {1305, 0xffffffffu}, {1351, 0xffffffffu},
    {1366, 0xffffffffu}, {1407, 0xffffffffu}, {1434, 0xffffffffu},
    {1442, 0xffffffffu}, {1458, 0xffffffffu}, {1512, 0xffffffffu},
    {1578, 0xffffffffu}, {1586, 0xffffffffu}, {1618, 0xffffffffu},
    {1647, 0xffffffffu}, {1660, 0xffffffffu}, {1742, 0xffffffffu}
};
static const struct libm_mask exp_a64[] = {
    {20, 0x60ffffe0u},
    {24, 0x3ffc00u},
    {28, 0x3ffc00u},
    {208, 0x3ffffffu},
    {224, 0x3ffffffu}
};
static const struct libm_mask log_a64[] = {
    {56, 0x60ffffe0u}, {60, 0x3ffc00u},   {92, 0x3ffc00u},  {232, 0x60ffffe0u},
    {236, 0x3ffc00u},  {508, 0x3ffffffu}, {512, 0x3ffffffu}
};
static const struct libm_mask pow_a64[] = {
    {56, 0x60ffffe0u},  {68, 0x3ffc00u},    {120, 0x3ffc00u},
    {324, 0x60ffffe0u}, {328, 0x3ffc00u},   {332, 0x3ffc00u},
    {952, 0x3ffffffu},  {1028, 0x3ffffffu}, {1064, 0x3ffffffu},
    {1148, 0x3ffffffu}
};
static const struct libm_sig {
    int arch, id;
    uint32_t len;
    uint64_t head, hash;
    const struct libm_mask* mask;
    int nmask;
} libm_sigs[] = {
    {KB_X86, 8, 492, 0xca8948c17e0f4866ull, 0xcc5f335ada7ba28aull, exp_x86,
     17}, /* exp */
    {KB_X86, 9, 669, 0x000000000000ba48ull, 0x8b67e71758a0421eull, log_x86,
     24}, /* log */
    {KB_X86, 10, 1800, 0x486653c07e0f4866ull, 0xb3dbd5815fb8984cull, pow_x86,
     39}, /* pow */
    {KB_A64, 8, 408, 0xd374f8239e660001ull, 0xc61a6c5ad7e1e06cull, exp_a64,
     5}, /* exp */
    {KB_A64, 9, 524, 0xd2f802409e660002ull, 0x32ea4a5704d712b5ull, log_a64,
     7}, /* log */
    {KB_A64, 10, 1276, 0x9e6600239e660004ull, 0xb44d517c9a7fc3eaull, pow_a64,
     10}, /* pow */
};
