import { readFileSync, writeFileSync } from 'node:fs';
import { readLeb, sections, skipImport, text } from '../wasm/binary.ts';

/**
 * Generates arch/wasm/kernel/syscall_adapters.c from the preprocessed syscall table
 * (make ... arch/wasm/kernel/syscall_table.i) and a built vmlinux.wasm.
 *
 * wasm's call_indirect traps unless the callee's signature matches exactly, so linux-wasm's dispatch,
 * which cast every handler to the argument count userspace passed, trapped whenever the two differed
 * (musl's pause() is ppoll with 4 of its 5 arguments; its futex calls pass 3 or 4 of 6). The
 * handler's real type is read from the built kernel, not from its prototype: SYSCALL_DEFINE's alias
 * leaves only __se_sys_x in a wasm build, a handler this configuration does not build is
 * sys_ni_syscall, and wasm32's rt_sigreturn takes no arguments whatever syscalls.h declares. Each
 * adapter reads the six argument slots (zeroed past those passed) and calls the table entry at that
 * exact type, joining two slots (low, high) for an i64 parameter. The adapters reference no sys_*
 * symbol, so rebuilding with them changes no handler's type; running this again on the rebuilt kernel
 * must reproduce the same file. `syscall-adapters.ts <syscall_table.i> <vmlinux.wasm> <out.c>`
 */
type Type = [number[], number[]];

/** name -> (params, results) as wasm value type codes, from the type, import, function and name sections */
function functionTypes(path: string): Map<string, Type> {
	const b = new Uint8Array(readFileSync(path));
	const types: Type[] = [];
	const funcTypes: number[] = [];
	const names = new Map<string, number>();
	for (const [id, , start, end] of sections(b)) {
		if (id === 1) {
			let [count, j] = readLeb(b, start);
			while (count--) {
				j++;
				const [np, a] = readLeb(b, j);
				const params = [...b.subarray(a, a + np)];
				const [nr, r] = readLeb(b, a + np);
				types.push([params, [...b.subarray(r, r + nr)]]);
				j = r + nr;
			}
		} else if (id === 2) {
			let [count, j] = readLeb(b, start);
			while (count--) {
				for (let s = 0; s < 2; s++) {
					const [n, k] = readLeb(b, j);
					j = k + n;
				}
				const kind = b[j++]!;
				if (kind === 0) funcTypes.push(readLeb(b, j)[0]);
				j = skipImport(b, kind, j);
			}
		} else if (id === 3) {
			let [count, j] = readLeb(b, start);
			while (count--) {
				const [t, k] = readLeb(b, j);
				funcTypes.push(t);
				j = k;
			}
		} else if (id === 0) {
			const [n, j0] = readLeb(b, start);
			if (text.decode(b.subarray(j0, j0 + n)) !== 'name') continue;
			let j = j0 + n;
			while (j < end) {
				const sub = b[j]!;
				const [subSize, at] = readLeb(b, j + 1);
				if (sub === 1) {
					let [count, k] = readLeb(b, at);
					while (count--) {
						const [index, k1] = readLeb(b, k);
						const [len, k2] = readLeb(b, k1);
						names.set(text.decode(b.subarray(k2, k2 + len)), index);
						k = k2 + len;
					}
				}
				j = at + subSize;
			}
		}
	}
	const out = new Map<string, Type>();
	for (const [name, index] of names)
		if (index < funcTypes.length) out.set(name, types[funcTypes[index]!]!);
	return out;
}

const I32 = 0x7f;
const I64 = 0x7e;
// sys_ni_syscall(void); the name section may list its function under one of its aliases
const NI: Type = [[], [I32]];

const [tableI, vmlinux, dst] = process.argv.slice(2);
const source = readFileSync(tableI!, 'utf8');
const size = Number(source.match(/sys_call_table\[(\d+)\]/)![1]);
const table = new Map<number, string>();
for (const m of source
	.slice(source.indexOf('sys_call_table['))
	.matchAll(/\[(\d+)\]\s*=\s*\(void \(\*\)\(void\)\)\(void\*\)\((\w+)\)/g))
	table.set(Number(m[1]), m[2]!);
const types = functionTypes(vmlinux!);
const find = (name: string) => types.get(name) ?? types.get('__se_' + name);
const out = [
	'// generated by gmux scripts/kernel/syscall-adapters.ts from the syscall table and a built',
	'// vmlinux; do not edit',
	'#include <asm/syscall.h>',
	'',
	'#define WASM_J64(i) (((unsigned long long)(unsigned long)a[(i) + 1] << 32) | (unsigned long)a[i])',
	''
];
const adapters = new Map<string, string>();
let unbuilt = 0;
const numbers = [...table.keys()].sort((a, b) => a - b);
for (const nr of numbers) {
	const name = table.get(nr)!;
	let found = find(name);
	if (!found) {
		unbuilt++;
		found = NI;
	}
	const [params, results] = found;
	if (results.length !== 1 || results[0] !== I32 || params.some((p) => p !== I32 && p !== I64))
		throw new Error(`${name}: unexpected wasm type ${params} -> ${results}`);
	const key = params.join(',');
	if (adapters.has(key)) continue;
	const decl: string[] = [];
	const args: string[] = [];
	let slot = 0;
	for (const p of params) {
		decl.push(p === I64 ? 'long long' : 'long');
		args.push(p === I64 ? `WASM_J64(${slot})` : `a[${slot}]`);
		slot += p === I64 ? 2 : 1;
	}
	if (slot > 6) throw new Error(`${name} needs ${slot} argument slots`);
	const fn = `wasm_call_${params.map((p) => (p === I64 ? 'j' : 'i')).join('') || 'v'}`;
	adapters.set(key, fn);
	out.push(
		`static long ${fn}(void (*f)(void), const long *a)`,
		'{',
		`\treturn ((long (*)(${decl.join(', ') || 'void'}))(void *)f)(${args.join(', ')});`,
		'}',
		''
	);
}
out.push(`long (* const wasm_syscall_callers[${size}])(void (*)(void), const long *) = {`);
for (const nr of numbers) {
	const name = table.get(nr)!;
	out.push(`\t[${nr}] = ${adapters.get((find(name) ?? NI)[0].join(','))}, /* ${name} */`);
}
out.push('};');
writeFileSync(dst!, out.join('\n') + '\n');
console.log(
	`${dst}: ${table.size} of ${size} numbers, ${adapters.size} call shapes, ${unbuilt} unbuilt`
);
