"""generates arch/wasm/kernel/syscall_adapters.c from the preprocessed syscall table
(make ... arch/wasm/kernel/syscall_table.i) and a built vmlinux.wasm.

wasm's call_indirect traps unless the callee's signature matches exactly, so linux-wasm's dispatch,
which cast every handler to the argument count userspace passed, trapped whenever the two differed
(musl's pause() is ppoll with 4 of its 5 arguments; its futex calls pass 3 or 4 of 6). The handler's
real type is read from the built kernel, not from its prototype: SYSCALL_DEFINE's alias leaves only
__se_sys_x in a wasm build, a handler this configuration does not build is sys_ni_syscall, and
wasm32's rt_sigreturn takes no arguments whatever syscalls.h declares. Each adapter reads the six
argument slots (zeroed past those passed) and calls the table entry at that exact type, joining two
slots (low, high) for an i64 parameter. The adapters reference no sys_* symbol, so rebuilding with them
changes no handler's type; running this again on the rebuilt kernel must reproduce the same file."""
import re
import sys


def leb(data, i):
    result = shift = 0
    while True:
        byte = data[i]
        i += 1
        result |= (byte & 0x7F) << shift
        shift += 7
        if byte < 0x80:
            return result, i


def function_types(path):
    """name -> (params, results) as wasm value type codes, from the type, import, function and name sections"""
    data = open(path, 'rb').read()
    types, func_types, names, imported = [], [], {}, 0
    i = 8
    while i < len(data):
        sid = data[i]
        size, i = leb(data, i + 1)
        end = i + size
        if sid == 1:
            count, j = leb(data, i)
            for _ in range(count):
                j += 1
                n, j = leb(data, j)
                params = list(data[j:j + n])
                j += n
                n, j = leb(data, j)
                results = list(data[j:j + n])
                j += n
                types.append((params, results))
        elif sid == 2:
            count, j = leb(data, i)
            for _ in range(count):
                n, j = leb(data, j)
                j += n
                n, j = leb(data, j)
                j += n
                kind = data[j]
                j += 1
                if kind == 0:
                    t, j = leb(data, j)
                    func_types.append(t)
                    imported += 1
                elif kind == 1:
                    j += 1
                    flags, j = leb(data, j)
                    _, j = leb(data, j)
                    if flags & 1:
                        _, j = leb(data, j)
                elif kind == 2:
                    flags, j = leb(data, j)
                    _, j = leb(data, j)
                    if flags & 1:
                        _, j = leb(data, j)
                elif kind == 3:
                    j += 2
                elif kind == 4:
                    j += 1
                    _, j = leb(data, j)
        elif sid == 3:
            count, j = leb(data, i)
            for _ in range(count):
                t, j = leb(data, j)
                func_types.append(t)
        elif sid == 0:
            n, j = leb(data, i)
            if data[j:j + n] == b'name':
                j += n
                while j < end:
                    sub = data[j]
                    sub_size, j = leb(data, j + 1)
                    sub_end = j + sub_size
                    if sub == 1:
                        count, k = leb(data, j)
                        for _ in range(count):
                            index, k = leb(data, k)
                            n, k = leb(data, k)
                            names[data[k:k + n].decode()] = index
                            k += n
                    j = sub_end
        i = end
    return {name: types[func_types[index]] for name, index in names.items() if index < len(func_types)}


I32, I64 = 0x7F, 0x7E
# sys_ni_syscall(void); the name section may list its function under one of its aliases
NI = ([], [I32])


def main(table_i, vmlinux, dst):
    text = open(table_i).read()
    size = int(re.search(r'sys_call_table\[(\d+)\]', text).group(1))
    table = {}
    body = text[text.index('sys_call_table['):]
    for m in re.finditer(r'\[(\d+)\]\s*=\s*\(void \(\*\)\(void\)\)\(void\*\)\((\w+)\)', body):
        table[int(m.group(1))] = m.group(2)
    types = function_types(vmlinux)
    out = ['// generated by gmux scripts/kernel/syscall-adapters.py from the syscall table and a built',
           '// vmlinux; do not edit', '#include <asm/syscall.h>', '',
           '#define WASM_J64(i) (((unsigned long long)(unsigned long)a[(i) + 1] << 32) | (unsigned long)a[i])', '']
    adapters, unbuilt = {}, 0
    for nr in sorted(table):
        name = table[nr]
        found = types.get(name) or types.get('__se_' + name)
        if found is None:
            unbuilt += 1
            found = NI
        params, results = found
        if results != [I32] or any(p not in (I32, I64) for p in params):
            sys.exit(f'{name}: unexpected wasm type {params} -> {results}')
        key = tuple(params)
        if key not in adapters:
            decl, args, slot = [], [], 0
            for p in params:
                decl.append('long long' if p == I64 else 'long')
                args.append(f'WASM_J64({slot})' if p == I64 else f'a[{slot}]')
                slot += 2 if p == I64 else 1
            if slot > 6:
                sys.exit(f'{name} needs {slot} argument slots')
            sig = ''.join('j' if p == I64 else 'i' for p in params) or 'v'
            fn = f'wasm_call_{sig}'
            adapters[key] = fn
            out += [f'static long {fn}(void (*f)(void), const long *a)', '{',
                    f'\treturn ((long (*)({", ".join(decl) or "void"}))(void *)f)({", ".join(args)});',
                    '}', '']
    out.append(f'long (* const wasm_syscall_callers[{size}])(void (*)(void), const long *) = {{')
    for nr in sorted(table):
        name = table[nr]
        params = (types.get(name) or types.get('__se_' + name) or NI)[0]
        out.append(f'\t[{nr}] = {adapters[tuple(params)]}, /* {name} */')
    out.append('};')
    open(dst, 'w').write('\n'.join(out) + '\n')
    print(f'{dst}: {len(table)} of {size} numbers, {len(adapters)} call shapes, {unbuilt} unbuilt')


if __name__ == '__main__':
    main(*sys.argv[1:])
